services:
  - type: web
    name: yolo-detection
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
